### ISSUE TITLE
Support to mongoose populate

### ISSUE THREAD

**Issue by adolfosbh** [jackytck/mongo-relay-connection#3]
Hi Jack,

Any plan to support mongoose populate feature [1] ?. What about a new options field (e.g populateArgs) to include the additional arguments to pass to the populate function of the final query ?

[1] http://mongoosejs.com/docs/populate.html

**Comment by jackytck** [comment]
Thanks for your suggestion. I will take a look at it.
At the time being, you may consider resolving the ref id in the nested level.

**Comment by adolfosbh** [comment]
Great !! I've created a simple PR I made it work in local from which you can start from (or pull it as it is)

Cheers,
Adolfo.

**Comment by jackytck** [comment]
{ populate: 'fieldName' } option is supported since v0.1.6.
Thanks for your suggestion.
